language: node_js
node_js:
    - 10
cache: yarn
install:
    - yarn
script:
   - yarn build
after_success:
    - cd .vuepress/dist
    - git init
    - git config --global user.name "${UESR_NAME}"
    - git config --global user.email "${UESR_EMAIL}"
    - git add -A
    - git commit -m 'deploy vuePress docs'
    - git push --quiet --force "https://${GIHUB_TOKEN}@${GIHUB_REF}" master:${P_BRANCH}